
package vista;

/**
 *
 * @author Francisco Javier Gómez Gamero
 */
public class PanelEditarMovimientos extends javax.swing.JPanel {

    /**
     * Creates new form PanelEditarMovimientos
     */
    public PanelEditarMovimientos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fecha = new rojeru_san.componentes.RSDateChooser();
        cbTipo = new javax.swing.JComboBox<>();
        cbCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbSubcategoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        campoNotas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoImporte = new javax.swing.JTextField();
        cancelarBtn = new javax.swing.JPanel();
        cancelarBtnTxt = new javax.swing.JLabel();
        guardarBtn = new javax.swing.JPanel();
        guardarBtnTxt = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fecha.setToolTipText("Fecha del movimiento");
        fecha.setColorBackground(new java.awt.Color(242, 242, 242));
        fecha.setColorButtonHover(new java.awt.Color(0, 134, 190));
        fecha.setColorDiaActual(new java.awt.Color(0, 134, 190));
        fecha.setColorForeground(new java.awt.Color(0, 0, 0));
        fecha.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fecha.setFormatoFecha("dd/MM/yyyy");
        fecha.setFuente(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fecha.setPlaceholder("");
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 30));

        cbTipo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingreso", "Gasto" }));
        jPanel1.add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 90, -1));

        cbCategoria.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel1.add(cbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 140, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setText("Fecha:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Tipo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Categoría:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("Subcategoría:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        cbSubcategoria.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel1.add(cbSubcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 150, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setText("Notas:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        campoNotas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel1.add(campoNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 210, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setText("Importe:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        campoImporte.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jPanel1.add(campoImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, -1, -1));

        cancelarBtn.setBackground(new java.awt.Color(0, 134, 190));

        cancelarBtnTxt.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        cancelarBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        cancelarBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarBtnTxt.setText("CANCELAR");
        cancelarBtnTxt.setToolTipText("Pulsa para salir sin guardar");
        cancelarBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout cancelarBtnLayout = new javax.swing.GroupLayout(cancelarBtn);
        cancelarBtn.setLayout(cancelarBtnLayout);
        cancelarBtnLayout.setHorizontalGroup(
            cancelarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        cancelarBtnLayout.setVerticalGroup(
            cancelarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cancelarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(cancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 120, 40));

        guardarBtn.setBackground(new java.awt.Color(0, 134, 190));
        guardarBtn.setToolTipText("");

        guardarBtnTxt.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        guardarBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        guardarBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardarBtnTxt.setText("GUARDAR");
        guardarBtnTxt.setToolTipText("Pulsa para crear el usuario");
        guardarBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout guardarBtnLayout = new javax.swing.GroupLayout(guardarBtn);
        guardarBtn.setLayout(guardarBtnLayout);
        guardarBtnLayout.setHorizontalGroup(
            guardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guardarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        guardarBtnLayout.setVerticalGroup(
            guardarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guardarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(guardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField campoImporte;
    public javax.swing.JTextField campoNotas;
    public javax.swing.JPanel cancelarBtn;
    public javax.swing.JLabel cancelarBtnTxt;
    public javax.swing.JComboBox<String> cbCategoria;
    public javax.swing.JComboBox<String> cbSubcategoria;
    public javax.swing.JComboBox<String> cbTipo;
    public rojeru_san.componentes.RSDateChooser fecha;
    public javax.swing.JPanel guardarBtn;
    public javax.swing.JLabel guardarBtnTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
