
package vista.Paneles;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Francisco Javier Gómez Gamero
 */
public class PanelCuentas extends javax.swing.JPanel {

    /**
     * Creates new form PanelCuentas
     */
    public PanelCuentas() {
        initComponents();
        
        //Modificaciones al JTable para mostrar las cuentas
        tablaCuentas.getTableHeader().setFont(new Font("Roboto", Font.BOLD, 14));
        tablaCuentas.getTableHeader().setOpaque(false);
        tablaCuentas.getTableHeader().setBackground(new Color(0,134,190));
        tablaCuentas.getTableHeader().setForeground(new Color(255,255,255));
        tablaCuentas.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelSaldo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        etiSaldoTotal = new javax.swing.JLabel();
        panelCuentas = new javax.swing.JScrollPane();
        tablaCuentas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        btnAdd = new javax.swing.JPanel();
        etiAdd = new javax.swing.JLabel();
        btnModificar = new javax.swing.JPanel();
        etiModificar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        etiElminar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        etiIngresosTotales = new javax.swing.JLabel();
        sumaIngresos = new javax.swing.JLabel();
        etiPagosTotales = new javax.swing.JLabel();
        sumaPagos = new javax.swing.JLabel();
        panelGastos = new javax.swing.JPanel();
        panelIngresos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(970, 600));
        setPreferredSize(new java.awt.Dimension(970, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiNombre.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        etiNombre.setText("Hola");
        jPanel1.add(etiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 510, 40));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("Todas tus cuentas:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        panelSaldo.setBackground(new java.awt.Color(255, 255, 255));
        panelSaldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelSaldo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelSaldo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 220, 10));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setText("Este es el saldo de todas las cuentas:");
        panelSaldo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        etiSaldoTotal.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        etiSaldoTotal.setText("saldo");
        etiSaldoTotal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panelSaldo.add(etiSaldoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 140, 50));

        jPanel1.add(panelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 250, 130));

        tablaCuentas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Alias", "IBAN", "Banco", "Saldo", "Movimientos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaCuentas.setFocusable(false);
        tablaCuentas.setGridColor(new java.awt.Color(255, 255, 255));
        tablaCuentas.setRowHeight(25);
        tablaCuentas.setRowMargin(1);
        tablaCuentas.setSelectionBackground(new java.awt.Color(255, 248, 236));
        tablaCuentas.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tablaCuentas.setShowGrid(false);
        tablaCuentas.setShowHorizontalLines(true);
        tablaCuentas.getTableHeader().setReorderingAllowed(false);
        panelCuentas.setViewportView(tablaCuentas);

        jPanel1.add(panelCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 630, 160));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("¡Así está tu saldo!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setBackground(new java.awt.Color(190, 56, 0));
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setLayout(new java.awt.GridBagLayout());

        etiAdd.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiAdd.setForeground(new java.awt.Color(255, 255, 255));
        etiAdd.setText("AÑADIR");
        etiAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.add(etiAdd, new java.awt.GridBagConstraints());

        panelMenu.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        btnModificar.setBackground(new java.awt.Color(190, 56, 0));
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setLayout(new java.awt.GridBagLayout());

        etiModificar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiModificar.setForeground(new java.awt.Color(255, 255, 255));
        etiModificar.setText("MODIFICAR");
        etiModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.add(etiModificar, new java.awt.GridBagConstraints());

        panelMenu.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 20));

        btnEliminar.setBackground(new java.awt.Color(190, 56, 0));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setLayout(new java.awt.GridBagLayout());

        etiElminar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiElminar.setForeground(new java.awt.Color(255, 255, 255));
        etiElminar.setText("ELIMINAR");
        etiElminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.add(etiElminar, new java.awt.GridBagConstraints());

        panelMenu.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 20));

        jPanel1.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 370, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiIngresosTotales.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        etiIngresosTotales.setText("ingresos");
        jPanel2.add(etiIngresosTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, -1));

        sumaIngresos.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        sumaIngresos.setForeground(new java.awt.Color(60, 179, 113));
        sumaIngresos.setText("ingresos");
        sumaIngresos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(sumaIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 140, 50));

        etiPagosTotales.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        etiPagosTotales.setText("pagos");
        jPanel2.add(etiPagosTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        sumaPagos.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        sumaPagos.setForeground(new java.awt.Color(220, 20, 60));
        sumaPagos.setText("pagos");
        jPanel2.add(sumaPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 250, 150));

        panelGastos.setBackground(new java.awt.Color(255, 255, 255));
        panelGastos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelGastos.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panelGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 420, 300));

        panelIngresos.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(panelIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 200, 300));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cuentaFoto.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 250, 170));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 600));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnAdd;
    public javax.swing.JPanel btnEliminar;
    public javax.swing.JPanel btnModificar;
    public javax.swing.JLabel etiAdd;
    public javax.swing.JLabel etiElminar;
    public javax.swing.JLabel etiIngresosTotales;
    public javax.swing.JLabel etiModificar;
    public javax.swing.JLabel etiNombre;
    public javax.swing.JLabel etiPagosTotales;
    public javax.swing.JLabel etiSaldoTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane panelCuentas;
    public javax.swing.JPanel panelGastos;
    public javax.swing.JPanel panelIngresos;
    public javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelSaldo;
    public javax.swing.JLabel sumaIngresos;
    public javax.swing.JLabel sumaPagos;
    public javax.swing.JTable tablaCuentas;
    // End of variables declaration//GEN-END:variables
}
