/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Paneles;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Francisco Javier Gómez Gamero
 */
public class PanelFichaFondo extends javax.swing.JPanel {
    private int idFondo;

    /**
     * Creates new form PanelFichaFondo
     */
    public PanelFichaFondo(int idFondo) {
        this.idFondo = idFondo;
        initComponents();
        
        //Modificaciones al JTable para mostrar las cuentas
        tablaMovimientos.getTableHeader().setFont(new Font("Roboto", Font.BOLD, 14));
        tablaMovimientos.getTableHeader().setOpaque(false);
        tablaMovimientos.getTableHeader().setBackground(new Color(0,134,190));
        tablaMovimientos.getTableHeader().setForeground(new Color(255,255,255));
        tablaMovimientos.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelCuentas = new javax.swing.JScrollPane();
        tablaMovimientos = new javax.swing.JTable();
        panelMenu = new javax.swing.JPanel();
        btnAdd = new javax.swing.JPanel();
        etiAdd = new javax.swing.JLabel();
        btnModificar = new javax.swing.JPanel();
        etiModificar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        etiElminar = new javax.swing.JLabel();
        PanelInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        etiFondo = new javax.swing.JLabel();
        etiIsin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        etiTipo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        etiMoneda = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        etiRiesgo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        etiParticipaciones = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        etiValor = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        etiSaldo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        etiMedia = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1150, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMovimientos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Tipo", "Participaciones", "Precio", "Importe", "Notas", "Total Partcipaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMovimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaMovimientos.setFocusable(false);
        tablaMovimientos.setGridColor(new java.awt.Color(255, 255, 255));
        tablaMovimientos.setRowHeight(25);
        tablaMovimientos.setRowMargin(1);
        tablaMovimientos.setSelectionBackground(new java.awt.Color(255, 248, 236));
        tablaMovimientos.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tablaMovimientos.setShowGrid(false);
        tablaMovimientos.setShowHorizontalLines(true);
        tablaMovimientos.getTableHeader().setReorderingAllowed(false);
        panelCuentas.setViewportView(tablaMovimientos);

        jPanel2.add(panelCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 820, 390));

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setBackground(new java.awt.Color(190, 56, 0));
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setLayout(new java.awt.GridBagLayout());

        etiAdd.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiAdd.setForeground(new java.awt.Color(255, 255, 255));
        etiAdd.setText("AÑADIR");
        etiAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.add(etiAdd, new java.awt.GridBagConstraints());

        panelMenu.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        btnModificar.setBackground(new java.awt.Color(190, 56, 0));
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setLayout(new java.awt.GridBagLayout());

        etiModificar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiModificar.setForeground(new java.awt.Color(255, 255, 255));
        etiModificar.setText("MODIFICAR");
        etiModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.add(etiModificar, new java.awt.GridBagConstraints());

        panelMenu.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 20));

        btnEliminar.setBackground(new java.awt.Color(190, 56, 0));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setLayout(new java.awt.GridBagLayout());

        etiElminar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiElminar.setForeground(new java.awt.Color(255, 255, 255));
        etiElminar.setText("ELIMINAR");
        etiElminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.add(etiElminar, new java.awt.GridBagConstraints());

        panelMenu.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 20));

        jPanel2.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 370, 40));

        PanelInfo.setBackground(new java.awt.Color(0, 134, 190));
        PanelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FONDO DE INVERSION");
        PanelInfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 256, -1));

        etiFondo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiFondo.setForeground(new java.awt.Color(255, 255, 255));
        etiFondo.setText("Nombre Fondo");
        PanelInfo.add(etiFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        etiIsin.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiIsin.setForeground(new java.awt.Color(255, 255, 255));
        etiIsin.setText("ISIN");
        PanelInfo.add(etiIsin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        PanelInfo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Código ISIN:");
        PanelInfo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Categoría:");
        PanelInfo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        etiTipo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiTipo.setForeground(new java.awt.Color(255, 255, 255));
        etiTipo.setText("tipo");
        PanelInfo.add(etiTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Divisa:");
        PanelInfo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        etiMoneda.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiMoneda.setForeground(new java.awt.Color(255, 255, 255));
        etiMoneda.setText("moneda");
        PanelInfo.add(etiMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nivel de Riesgo:");
        PanelInfo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        etiRiesgo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiRiesgo.setForeground(new java.awt.Color(255, 255, 255));
        etiRiesgo.setText("riesgo");
        PanelInfo.add(etiRiesgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cotización actual:");
        PanelInfo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        etiParticipaciones.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiParticipaciones.setForeground(new java.awt.Color(255, 255, 255));
        etiParticipaciones.setText("participaciones");
        PanelInfo.add(etiParticipaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nº Participaciones:");
        PanelInfo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        etiValor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiValor.setForeground(new java.awt.Color(255, 255, 255));
        etiValor.setText("valor");
        PanelInfo.add(etiValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("VALOR ACTUAL");
        PanelInfo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        etiSaldo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        etiSaldo.setForeground(new java.awt.Color(255, 255, 255));
        etiSaldo.setText("saldo");
        PanelInfo.add(etiSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, 10));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Precio Medio Compra:");
        PanelInfo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        etiMedia.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        etiMedia.setForeground(new java.awt.Color(255, 255, 255));
        etiMedia.setText("precio medio");
        PanelInfo.add(etiMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        PanelInfo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 240, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        PanelInfo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 240, 10));

        jPanel2.add(PanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 6, -1, 520));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("MOVIMIENTOS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInfo;
    public javax.swing.JPanel btnAdd;
    public javax.swing.JPanel btnEliminar;
    public javax.swing.JPanel btnModificar;
    public javax.swing.JLabel etiAdd;
    public javax.swing.JLabel etiElminar;
    public javax.swing.JLabel etiFondo;
    public javax.swing.JLabel etiIsin;
    public javax.swing.JLabel etiMedia;
    public javax.swing.JLabel etiModificar;
    public javax.swing.JLabel etiMoneda;
    public javax.swing.JLabel etiParticipaciones;
    public javax.swing.JLabel etiRiesgo;
    public javax.swing.JLabel etiSaldo;
    public javax.swing.JLabel etiTipo;
    public javax.swing.JLabel etiValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JScrollPane panelCuentas;
    public javax.swing.JPanel panelMenu;
    public javax.swing.JTable tablaMovimientos;
    // End of variables declaration//GEN-END:variables
}
